"""Writes play/art.js: portraits, walking sprites (front and back) and the player presets.

Run from the repo root: python3 design/build_art.py
"""
import json
import os
import sys

sys.path.insert(0, os.path.dirname(__file__))
import characters as c  # noqa: E402

HAIRS = ["#2A1E16", "#6B4226", "#B5863A", "#A8461F", "#B9B2A6"]
NPCS = ["ruth", "pruitt", "brandt", "cole", "ames", "clerk", "drummer"]
EXTRA = {
    # Background townsfolk and the rail foreman, drawn with the same kit.
    "foreman": dict(skin="#D19C6E", hair="#2A1E16", hairstyle="short", shirt="#B5532E", rolled=True, suspenders="#3A2A20",
                    pants="#4A4A52", boots="#2A2420", mustache="#2A1E16", hat=("straw", "#C9A86A"), mouth="flat"),
    "folk1": dict(skin="#EBC09A", hair="#6B4226", hairstyle="bun", shirt="#A8462E", dress="#A8462E", apron="#EFE6D2",
                  boots="#3A2A20", mouth="smile", buttons=False, belt=False),
    "folk2": dict(skin="#A86E45", hair="#2A1E16", hairstyle="short", shirt="#E8DCC0", coat="#6B4A32", pants="#4A4A52",
                  boots="#2A2420", hat=("bowler", "#4A3A2E"), mustache="#2A1E16", mouth="flat"),
    "folk3": dict(skin="#F6D5B8", hair="#B5863A", hairstyle="short", shirt="#3E6C9A", rolled=True, suspenders="#7A4A2A",
                  pants="#6B5A44", boots="#4A3222", hat=("cap", "#7A6A52"), mouth="grin"),
    "folk4": dict(skin="#4E2E1C", hair="#2A1E16", hairstyle="parted", shirt="#E6C77A", dress="#5E7A4E",
                  boots="#3A2A20", hat=("bonnet", "#F2EBDD"), mouth="soft", buttons=False, belt=False),
}


def player(si, hi):
    cc = c.jonah_with_skin(c.SKINS[si])
    cc["hair"] = HAIRS[hi]
    return cc


out = {"npc": {}, "front": {}, "back": {}, "player": {}, "playerFront": {}, "playerBack": {}}
for k in NPCS:
    out["npc"][k] = c.figure(k, c.CAST[k], 64, 64, view="portrait")
for k, cc in [(k, c.CAST[k]) for k in NPCS] + list(EXTRA.items()):
    out["front"][k] = c.figure(k + "f", cc, 120, 200)
    out["back"][k] = c.figure(k + "b", cc, 120, 200, view="back")
for si in range(len(c.SKINS)):
    for hi in range(len(HAIRS)):
        cc = player(si, hi)
        key = f"{si}-{hi}"
        out["player"][key] = c.figure("p", cc, 64, 64, view="portrait")
        out["playerFront"][key] = c.figure("pf", cc, 120, 200)
        out["playerBack"][key] = c.figure("pb", cc, 120, 200, view="back")
meta = {"skins": c.SKINS, "hairs": HAIRS, "cast": {k: {"name": c.ROLES[k][0], "role": c.ROLES[k][1]} for k in c.CAST}}
with open("play/art.js", "w") as fh:
    fh.write("// Generated by design/build_art.py from design/characters.py. Character art as inline SVG.\n")
    fh.write("export const ART = " + json.dumps(out) + ";\n")
    fh.write("export const LOOK = " + json.dumps(meta) + ";\n")
print(os.path.getsize("play/art.js"), "bytes")
